# Generated by Django 4.1.1 on 2022-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
